version: '3.9'

services:
  smart_web:
    image: breast_cancer_docker_img
    build: .
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

